env:
  global:
    - CC_TEST_REPORTER_ID=3d60ec942f3f9a663f8bc19e3583eb6c016726a618283052ef628478c6e24603

dist: xenial
language: python
python: "3.7"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install circuitpython-build-tools

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# command to run tests
script:
  - pytest --cov=src
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
